<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://server.webservice.keda.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="SpzxoutServiceImplService" targetNamespace="http://server.webservice.keda.com/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://server.webservice.keda.com/" elementFormDefault="unqualified" targetNamespace="http://server.webservice.keda.com/" version="1.0">

  <xs:element name="DoCommand" type="tns:DoCommand"/>

  <xs:element name="DoCommandResponse" type="tns:DoCommandResponse"/>

  <xs:complexType name="DoCommand">
    <xs:sequence>
      <xs:element minOccurs="0" name="xml" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="DoCommandResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="DoCommandResponse">
    <wsdl:part element="tns:DoCommandResponse" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="DoCommand">
    <wsdl:part element="tns:DoCommand" name="parameters">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="ISpzxoutService">
    <wsdl:operation name="DoCommand">
      <wsdl:input message="tns:DoCommand" name="DoCommand">
    </wsdl:input>
      <wsdl:output message="tns:DoCommandResponse" name="DoCommandResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SpzxoutServiceImplServiceSoapBinding" type="tns:ISpzxoutService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="DoCommand">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="DoCommand">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="DoCommandResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SpzxoutServiceImplService">
    <wsdl:port binding="tns:SpzxoutServiceImplServiceSoapBinding" name="SpzxoutServiceImplPort">
      <soap:address location="http://localhost:8125/jkzx/ws/spzx"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>